parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
env:
  node: true
  jest: true
root: true
plugins:
  - '@typescript-eslint'
  - 'unicorn'
  - 'import'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
rules:
  no-shadow:
    - error
  no-duplicate-imports:
    - error
    - includeExports: true
  no-template-curly-in-string: error
  block-scoped-var: error
  curly:
    - error
    - multi-line
  eqeqeq: error
  max-classes-per-file: off
  no-else-return:
    - error
    - allowElseIf: false
  no-implicit-coercion: error
  no-labels: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-return-await: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  prefer-promise-reject-errors: error
  radix: error
  no-undefined: off
  array-bracket-newline:
    - error
    - consistent
  comma-dangle:
    - error
    - always-multiline
  comma-style: error
  eol-last: error
  key-spacing: error
  keyword-spacing: error
  new-parens: error
  no-bitwise: warn
  no-lonely-if: warn
  no-multiple-empty-lines: error
  no-nested-ternary: error
  no-new-object: error
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline: error
  object-curly-spacing:
    - error
    - always
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  switch-colon-spacing: error
  arrow-parens:
    - error
    - always
  no-console: error
  arrow-spacing: error
  generator-star-spacing:
    - error
    - after
  no-confusing-arrow: error
  no-useless-computed-key: error
  no-useless-rename: error
  object-shorthand:
    - error
    - always
  prefer-arrow-callback: warn
  prefer-destructuring: error
  rest-spread-spacing:
    - error
    - never
  template-curly-spacing: error
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/consistent-function-scoping: error
  unicorn/explicit-length-check: error
  "@typescript-eslint/no-extra-parens":
    - error
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/member-ordering":
    - error
    - default:
        - field
        - constructor
        - public-method
        - private-method
  "@typescript-eslint/brace-style":
    - error
    - 1tbs
  "@typescript-eslint/indent":
    - error
    - 2
    - SwitchCase: 1
  "@typescript-eslint/quotes":
    - error
    - single
    - avoidEscape: true
  "@typescript-eslint/func-call-spacing":
    - error
    - never
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: no-public
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/prefer-for-of": warn
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/no-unnecessary-type-arguments": warn
  "@typescript-eslint/prefer-function-type": warn
  "@typescript-eslint/prefer-readonly": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/member-delimiter-style": error
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_|Console|CONTEXT"
  "@typescript-eslint/method-signature-style":
    - error
    - property